# Generated by Django 5.1.2 on 2024-11-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_category_category_id_alter_category_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
