# Generated by Django 5.1.2 on 2024-11-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='y_category_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
